disable profiling on Mac because it does not work
in particular, this is the error i observe:

FAILED: icc -o /Users/jrhammon/Work/GTFOCK/OptErd/test/unit-test
/Users/jrhammon/Work/GTFOCK/OptErd/build/test/unit-test.c.o
/Users/jrhammon/Work/GTFOCK/OptErd/build/test/screening.c.o
-L/Users/jrhammon/Work/GTFOCK/OptErd/lib -lcint -lerd -loed
-static-intel -no-intel-extensions -lifcore -openmp
Undefined symbols for architecture x86_64:
  "_erd_ticks", referenced from:
      _erd__1111_csgto in liberd.a(erd__1111_csgto.c.o)
      _erd__csgto in liberd.a(erd__csgto.c.o)
      _erd__e0f0_pcgto_block in liberd.a(erd__e0f0_pcgto_block.c.o)
ld: symbol(s) not found for architecture x86_64
ninja: build stopped: subcommand failed.